### ISSUE TITLE
Show gnome-control-center panels directly in app

### ISSUE THREAD

**Issue by friday** [friday/Legacy-Ulauncher-Fork#20]
Gnome integrates their settings panels in their own launcher (see the middle part of the picture), and for this reason they made them not display as normal apps. This however causes them to not show in third party launchers at all. You can enable them by copying the desktop entry locally and [overriding NoDisplay](https://github.com/friday/ulauncher-gnome-settings#create-or-modify-desktop-entries), in which case they will show up in Ulauncher, but also show up twice in Gnome's own launcher (actually three times counting the desktop entry showing up as a file)

![2021-06-30_19-09](https://user-images.githubusercontent.com/515120/124003084-cff37600-d9d6-11eb-8805-a6e449260652.png)

In Ulauncher it only shows up once (if you do this):
![2021-06-30_19-33](https://user-images.githubusercontent.com/515120/124006206-404fc680-d9da-11eb-9441-16292224ece0.png)

It would be very easy to change the behavior to show these as normal apps. Now that we support `ShowIn`, they would also only show when your current session is gnome.

I'm considering making this the default rather than adding another option. If people complain they can opt out.

See https://github.com/friday/ulauncher-gnome-settings#modify-ulauncher-not-recommended

**Comment by RedBearAK** [comment]
Similar issue exists with the KDE System Settings app, the "KCM" modules are not searchable except by using the `krunner` framework. 

That might be changing in the future. This is referencing Albert Launcher, but I assume that Ulauncher looks for desktop files in the same way: 

https://bugs.kde.org/show_bug.cgi?id=433566

**Comment by friday** [comment]
> Similar issue exists with the KDE System Settings app, the "KCM" modules are not searchable except by using the `krunner` framework.
> 
> That might be changing in the future. This is referencing Albert Launcher, but I assume that Ulauncher looks for desktop files in the same way:
> 
> https://bugs.kde.org/show_bug.cgi?id=433566

I don't have the time to be testing or reading issue trackers on KDE unfortunately. I possibly will be have more time for things like this later, but for now the only way to solve this is if someone who runs KDE could look at the commit to figure out how to submit a PR. If they have Desktop Entries for all the panels they can look at the desktop entries for the settings (should be in /usr/share/applications/ I think) to see if they exist to begin with, if `NoDisplay` is set to true, if they're hidden from other environments with `OnlyShowIn`, and if there's a clear way to distinguish them from other apps. The gnome-panels apps have all of that. The Desktop entries all have the lines `Exec gnome-control-center ...`, so I can make an exception for this case in particular.

I'm going to add this soon for Gnome, and I won't add any setting. If people don't want them to be shown, then they can file an issue instead.
