### ISSUE TITLE
All apps launched with Ulauncher crash if one crashes, or if Ulauncher is killed

### ISSUE THREAD

**Issue by friday** [friday/Legacy-Ulauncher-Fork#3]
See https://github.com/Ulauncher/Ulauncher/issues/754

**Comment by friday** [comment]
This was fixed in a3b6dcf by adding a custom handler to open the app instead of relying on [`AppInfo.launch()`](https://lazka.github.io/pgi-docs/Gio-2.0/classes/AppInfo.html#Gio.AppInfo.launch) or [`DesktopAppInfo.launch_uris_as_manager()`](https://lazka.github.io/pgi-docs/Gio-2.0/classes/DesktopAppInfo.html#Gio.DesktopAppInfo.launch_uris_as_manager). The GTK Python APIs may be safer or the "right" way, but I wasted hours trying to solve this with them.

This may cause issues opening apps with strange things in `Exec`. I tried some combinations though, and they all worked.

Also worth looking into: https://askubuntu.com/a/5174/420716, but I think the custom methos is needed either way for custom terminal emulator support.

**Comment by troycurtisjr** [comment]
So from what I can tell, this really only happened with apps that had "Terminal=True" and a customer terminal command was defined. At least that was the only scenario I could reproduce the situation in. Were you also seeing the behavior when using `AppInfo.launch()` without a custom terminal and Terminal=True application?

**Comment by friday** [comment]
> So from what I can tell, this really only happened with apps that had "Terminal=True" and a customer terminal command was defined. At least that was the only scenario I could reproduce the situation in. Were you also seeing the behavior when using `AppInfo.launch()` without a custom terminal and Terminal=True application?

No. It happened every time.

Install regular Ulauncher. Run from shell. Launch lots of apps and ctrl+c. The app you launched will all exit. Same thing with this commit if you remove `start_new_session=True`.

**Comment by troycurtisjr** [comment]
Ah! Yeah that makes sense since Ctrl-C actually sends the SIGINT to the entire session group, roughly equivalent to `kill -SIGINT -<pid>`. In my tests I was still launching under systemd and directly killing ulauncher with `kill`.
