### ISSUE TITLE
No logging output from extensions

### ISSUE THREAD

**Issue by niraami** [friday/Legacy-Ulauncher-Fork#33]
### Steps to reproduce
1. Install Ulauncher-Revived (via AUR, or similar) and the [demo extension](https://github.com/Ulauncher/ulauncher-demo-ext)
2. Run Ulauncher via `ulauncher -v` (or also `--dev`)

### Current behavior
No logging from within the extension (or other installed extensions, like the [spotify-api](https://github.com/the-lay/ulauncher-spotify-api)) is visible in the console. This does lead me to believe that I'm doing something wrong, but I've studied the [Ulauncher logging documentation](http://docs.ulauncher.io/en/latest/extensions/debugging.html), [python documentation](https://docs.python.org/3/howto/logging.html), stackoverflow questions, other extensions, etc, etc. This still leaves the possibility that my setup is somehow causing issues if others can't reproduce this.
At this point I've tried everything I can think of:
- using `logging` directly or even `print()` instead of the logger instance
- trying all other logging levels
- changing logging verbosity via `setLevel` or `basicConfig` on the either the `logger` instance, or the `logging` class itself.
- searching for a possible log file somewhere in `/tmp` or `~/.cache`
- studying both of the `setup_logging` scripts for any clues ([ulauncher/utils/setup_logging.py](https://github.com/friday/Ulauncher-Revived/blob/dev/ulauncher/utils/setup_logging.py) & [ulauncher/api/client/setup_logging.py](https://github.com/friday/Ulauncher-Revived/blob/dev/ulauncher/api/client/setup_logging.py))

### Expected behavior
Logs from extensions should be printed alongside other logs from Ulauncher itself, or stored in a separate file if needed.

### Environment
**Ulauncher version**: `ulauncher DEV` from [AUR](https://aur.archlinux.org/packages/ulauncher-revived-git/), same behaviour in Ulauncher 5.11 from [AUR](https://aur.archlinux.org/packages/ulauncher)
**Linux distro**: Arch Linux (Linux 5.12.15-arch1-1)
**Desktop environment**: N/A

### Logs
https://gist.github.com/niraami/c755ef96141434f35f12f0da4a9550f5

**Comment by friday** [comment]
Thank you for the bug report. I can confirm this is the case for me too.

I don't know when this happened, but it wasn't my my fork. It could be a global Python thing, or an earlier change in Ulauncher that broke this. If you or someone else have the ability I would appreciate help, since my time is limited.

**Comment by friday** [comment]
It was pretty easy to locate the issue. The ulauncher dev wanted to catch extensions crashing and show a message based on that. I pushed a commit that returns the behavior to printing out the errors, but now it doesn't catch the errors and won't show messages when they crash.

Will try to make it work both ways in a following commit.

**Comment by niraami** [comment]
Thank you for taking your time to fix this :)
